const STAGES = {
  RECEIVED: 'RECEIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  PENDING_PARTS: 'PENDING_PARTS',
  COMPLETED: 'COMPLETED',
  DELIVERED: 'DELIVERED',
};

const SERVICE_TYPES = {
  GENERAL_SERVICE: 'GENERAL_SERVICE',
  REPAIR: 'REPAIR',
  WASH: 'WASH',
  INSPECTION: 'INSPECTION',
};

module.exports = {
  STAGES,
  SERVICE_TYPES,
};
