const STAGES = {
  INTAKE: 'INTAKE',
  DIAGNOSIS: 'DIAGNOSIS',
  IN_SERVICE: 'IN_SERVICE',
  QC_CHECK: 'QC_CHECK',
  READY: 'READY',
  RECEIVED: 'RECEIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  PENDING_PARTS: 'PENDING_PARTS',
  COMPLETED: 'COMPLETED',
  DELIVERED: 'DELIVERED',
};

const SERVICE_TYPES = {
  GENERAL_SERVICE: 'GENERAL_SERVICE',
  REPAIR: 'REPAIR',
  INSPECTION: 'INSPECTION',
  CUSTOM: 'CUSTOM',
};

const PRIORITIES = {
  NORMAL: 'NORMAL',
  URGENT: 'URGENT',
  EXPRESS: 'EXPRESS',
  WASH: 'WASH',
  INSPECTION: 'INSPECTION',
};

module.exports = {
  STAGES,
  SERVICE_TYPES,
  PRIORITIES,
};
